version: '2'

services:

  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/blog.conf:/etc/nginx/sites-enabled/blog.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    links:
      - ghost
    restart: always

  ghost:
    build: ./ghost
    container_name: ghost
    hostname: ghost
    image: mvkvl/ghost
    volumes:
      - /opt/docker/ghost/data:/var/lib/ghost/content
    #ports:
    #  - "2368:2368"
    environment:
      - NODE_ENV=production
    restart: always
